name: Docker Build and Push To DockerHub Container Registry

on:
  push:
    branches:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker CLI
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short Git commit hash
        id: git_commit
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Build and push Docker image to Docker Hub
        run: |
          echo "building images in progress..."
          docker build -t abodaa/ecommerce-project_web:${{ steps.git_commit.outputs.hash }} -f Dockerfile .
          echo "pushing images in progress..."
          docker push abodaa/ecommerce-project_web:${{ steps.git_commit.outputs.hash }}
